# Copyright (c) 2020 Red Hat, Inc.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-ui
  labels:
    app: {{ .Values.search.name }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: search-ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.search.name }}
      component: search-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.search.name }}
        component: search-ui
        release: {{ .Release.Name }}
        chart: {{.Chart.Name}}-{{.Chart.Version}}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: search-ui
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.global.arch }}
                - {{ . }}
                {{- end }}
        {{- with .Values.affinity.podAntiAffinity }}
        podAntiAffinity: 
{{ toYaml . | indent 10 }}
        {{- end }}
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
      - name: search-ui
        image: {{ .Values.global.imageOverrides.search_ui }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        resources:
        {{- toYaml .Values.search.ui.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        - name: API_SERVER_URL
          value: https://kubernetes.default.svc:443
        - name: SEARCH_API_URL
          value: https://search-search-api:4010/searchapi
        - name: FRONTEND_URL
          value: "https://multicloud-console.{{ .Values.ocpingress }}/search/"
        - name: OAUTH2_REDIRECT_URL
          value: https://multicloud-console.{{ .Values.ocpingress }}/search/login/callback
        - name: PORT
          value: '3000'
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenessProbe
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readinessProbe
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret }}
      {{- end }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
