# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

{{- if .Values.search.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "search.fullname" . }}-create-redis-secret
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "search.fullname" . }}-create-redis-secret
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-5"
data:
  create-secret.sh: |
    #!/bin/sh
    ulimit -u
    if  (!(kubectl get secret {{ .Release.Name }}-redisgraph-user-secrets));
    then
      kubectl create secret generic {{ .Release.Name }}-redisgraph-user-secrets --from-literal=redispwd=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1) --dry-run -o yaml | kubectl apply -f -
    fi
{{- end }}
