# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "search.fullname" . }}-search-collector
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    component: "search-collector"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "search.name" . }}
      component: "search-collector"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "search.name" . }}
        component: "search-collector"
        release: {{ .Release.Name }}
        chart: {{ template "search.chart" . }}
        heritage: {{ .Release.Service }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.global.arch }}
                - {{ . }}
                {{- end }}
              - key: management
                operator: In
                values:
                - "true"
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
      - name: collector
        image: "{{ .Values.search.collector.image.repository }}:{{ .Values.search.collector.image.tag }}"
        imagePullPolicy: {{ .Values.search.collector.image.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        env:
        - name: DEPLOYED_IN_HUB
          value: "true"
        - name: CLUSTER_NAME
          value: local-cluster
        - name: AGGREGATOR_URL
          value: 'https://{{ template "search.fullname" . }}-search-aggregator:3010'
        resources:
        {{- toYaml .Values.search.collector.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 15
          periodSeconds: 60
        volumeMounts:
        - name: icp-search-certs
          mountPath: /sslcert
        - name: {{ .Release.Name }}-tiller-client-certs
          mountPath: /helmcerts
      {{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.pullSecret }}
      {{- end }}
      volumes:
      - name: icp-search-certs
        secret:
          secretName: {{ .Release.Name }}-search-secrets
      - name: {{ .Release.Name }}-tiller-client-certs
        secret:
          secretName: {{ .Release.Name }}-tiller-client-certs
          optional: true
      hostIPC: false
      hostNetwork: false
      hostPID: false
      {{- if .Values.global.nodeSelector.enabled }}
      nodeSelector:
      {{- if .Values.global.nodeSelector.os }}
        "beta.kubernetes.io/os" : {{ .Values.global.nodeSelector.os }}
      {{- end }}
      {{- if .Values.global.nodeSelector.customLabelSelector }}
        {{ .Values.global.nodeSelector.customLabelSelector }} : {{ .Values.global.nodeSelector.customLabelValue}}
      {{- end }}
      {{- end }}
